const canvas=document.querySelector("#root-field");
const context=canvas.getContext("2d",{alpha:false});
const system=await fetch(new URL("system.json",import.meta.url),{cache:"no-store"}).then(response=>response.json());
const drift=await fetch(new URL("drift.json",import.meta.url),{cache:"no-store"}).then(response=>response.json());
const connected=new Map(system.nodes.map(node=>[node.id,system.relations.filter(relation=>relation.from===node.id||relation.to===node.id)]));
let width=0,height=0,dpr=1,selected=null,lastTime=0;
const pointer={x:0,y:0,active:false,pressure:0};
const nodes=system.nodes.map((source,index)=>({source,x:0,y:0,vx:0,vy:0,r:source.id==="root-logos"?8:3.2+(connected.get(source.id).length*.55),phase:index*.91}));

function resize(){dpr=Math.min(devicePixelRatio||1,2);width=innerWidth;height=innerHeight;canvas.width=width*dpr;canvas.height=height*dpr;context.setTransform(dpr,0,0,dpr,0,0);seed()}
function seed(){const radius=Math.min(width,height)*.31;nodes.forEach((node,index)=>{if(node.source.id==="root-logos"){node.x=width*.5;node.y=height*.5;return}const a=-Math.PI/2+(index/(nodes.length-1))*Math.PI*2;node.x=width*.5+Math.cos(a)*radius*(.72+(index%3)*.12);node.y=height*.5+Math.sin(a)*radius*(.55+(index%2)*.18)})}
function step(time){const dt=Math.min(2,(time-lastTime)/16.67||1);lastTime=time;context.fillStyle="#030303";context.fillRect(0,0,width,height);
  for(const relation of system.relations){const a=nodes.find(node=>node.source.id===relation.from),b=nodes.find(node=>node.source.id===relation.to);const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,target=Math.min(width,height)*(.17+((hash(relation.id)%17)/100));const force=(d-target)*.000012*dt;a.vx+=dx/d*force;a.vy+=dy/d*force;b.vx-=dx/d*force;b.vy-=dy/d*force}
  for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const a=nodes[i],b=nodes[j],dx=b.x-a.x,dy=b.y-a.y,d2=dx*dx+dy*dy+1,force=Math.min(.009,72/d2)*dt;a.vx-=dx*force;a.vy-=dy*force;b.vx+=dx*force;b.vy+=dy*force}
  for(const node of nodes){const dx=width*.5-node.x,dy=height*.5-node.y;node.vx+=dx*.0000015*dt;node.vy+=dy*.0000015*dt;if(pointer.active){const px=node.x-pointer.x,py=node.y-pointer.y,d2=px*px+py*py+520,force=Math.min(.014,(pointer.pressure+1)*92/d2)*dt;node.vx+=px*force;node.vy+=py*force}const margin=44;if(node.x<margin)node.vx+=(margin-node.x)*.0007*dt;if(node.x>width-margin)node.vx-=(node.x-width+margin)*.0007*dt;if(node.y<margin)node.vy+=(margin-node.y)*.0007*dt;if(node.y>height-margin)node.vy-=(node.y-height+margin)*.0007*dt;node.vx*=.982;node.vy*=.982;node.x+=node.vx*dt;node.y+=node.vy*dt;node.x=Math.max(18,Math.min(width-18,node.x));node.y=Math.max(18,Math.min(height-18,node.y))}
  drawRelations(time);drawNodes(time);requestAnimationFrame(step)}
function drawRelations(time){for(const relation of system.relations){const a=nodes.find(node=>node.source.id===relation.from),b=nodes.find(node=>node.source.id===relation.to),active=selected&&(relation.from===selected.source.id||relation.to===selected.source.id);context.beginPath();context.moveTo(a.x,a.y);const mx=(a.x+b.x)/2,my=(a.y+b.y)/2;context.quadraticCurveTo(mx,my+Math.sin(time*.0002+hash(relation.id))*.7,b.x,b.y);context.strokeStyle=active?"rgba(178,32,25,.72)":"rgba(220,220,212,.13)";context.lineWidth=active?1:.55;context.stroke()}}
function drawNodes(time){for(const node of nodes){const active=node===selected,pulse=1+Math.sin(time*.0012+node.phase)*.09;context.beginPath();context.arc(node.x,node.y,node.r*pulse+(active?3:0),0,Math.PI*2);context.fillStyle=active?"#e9e9e4":node.source.id==="root-logos"?"#8e8e87":"#55554f";context.fill();if(node.source.id==="root-logos"){context.beginPath();context.arc(node.x,node.y,node.r*2.4+pulse,0,Math.PI*2);context.strokeStyle=drift.items.length?"rgba(178,32,25,.4)":"rgba(233,233,228,.25)";context.lineWidth=.7;context.stroke()}}}
function hash(value){let result=0;for(let i=0;i<value.length;i++)result=(result*31+value.charCodeAt(i))>>>0;return result}
function nearest(x,y,radius=30){let match=null,distance=radius;for(const node of nodes){const d=Math.hypot(node.x-x,node.y-y);if(d<distance){distance=d;match=node}}return match}
function inspect(node){selected=node;const panel=document.querySelector("#field-reading");if(!node){panel.hidden=true;return}document.querySelector("#reading-kind").textContent=node.source.kind;document.querySelector("#reading-name").textContent=node.source.name;document.querySelector("#reading-authority").textContent=node.source.authority;document.querySelector("#reading-relations").textContent=connected.get(node.source.id).length;document.querySelector("#reading-status").textContent=node.source.status;panel.hidden=false}
canvas.addEventListener("pointermove",event=>{pointer.x=event.clientX;pointer.y=event.clientY;pointer.active=true;pointer.pressure=event.pressure||.5});canvas.addEventListener("pointerleave",()=>pointer.active=false);canvas.addEventListener("pointerdown",event=>inspect(nearest(event.clientX,event.clientY,event.pointerType==="touch"?42:30)));document.querySelector("#close-reading").addEventListener("click",()=>inspect(null));document.querySelector("#mark").addEventListener("click",()=>{selected=null;document.querySelector("#field-reading").hidden=true;nodes.forEach(node=>{node.vx*=.2;node.vy*=.2})});
addEventListener("resize",resize);resize();if(matchMedia("(prefers-reduced-motion: reduce)").matches)nodes.forEach(node=>{node.vx=0;node.vy=0});requestAnimationFrame(step);
